# This file is the main config file for the service.
#
# For full config options, check the docs:
#    docs.serverless.com

service: GAToolBackend

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  role: arn:aws:iam::336977810532:role/service-role/GAToolRole
  profile: aws-arthurlockman
  stage: production
  environment: # Environment variables available to the whole service
    FRC_API_KEY: ${ssm:frc-api-key~true}
    TBA_API_HEADER: ${ssm:tba-api-header~true}
    TBA_API_KEY: ${ssm:tba-api-token~true}

functions: # TODO: outline all functions
  GetEvents:
    handler: handler.GetEvents
    description: Get events for a specific year
    events:
      - http:
          path: api/{year}/events
          method: get
          request:
            parameters:
              paths:
                year: true
  GetEventTeams:
    handler: handler.GetEventTeams
    description: Get teams for a specific event for a specific year
    events:
      - http:
          path: api/{year}/teams/{eventCode}/{page}
          method: get
          request:
            parameters:
              paths:
                year: true
                eventCode: true
                page: true
  GetTeamAwards:
    handler: handler.GetTeamAwards
    description: Get awards for a specific team in a specific year
    events:
      - http:
          path: api/{year}/awards/{teamNumber}
          method: get
          request:
            parameters:
              paths:
                year: true
                teamNumber: true
  GetEventScores:
    handler: handler.GetEventScores
    description: Get scores for a specific event with a year, competition level, start, and end
    events:
      - http:
          path: api/{year}/scores/{eventCode}/{tournamentLevel}/{start}/{end?}
          method: get
          request:
            parameters:
              paths:
                year: true
                eventCode: true
                tournamentLevel: true
                start: true
                end: false

# TODO: leverage API Gateway caching for requests
# TODO: add custom domain name mapping: https://stackoverflow.com/a/39595088
# TODO: outline resources and tables needed for the service

plugins:
  - serverless-plugin-typescript
  - serverless-offline
